# Prose configuration file
# Documentation: https://docs.prose.org/references/pod-config

# See https://docs.prose.org/references/pod-config/#brandingconfig.
[branding]
company_name = "{your_company_name}"

# See https://docs.prose.org/references/pod-config/#serverconfig.
[server]
domain = "{your_domain}" # Once set, cannot be changed.

# See https://docs.prose.org/references/pod-config/#notifyemailconfig.
[notifiers.email]
smtp_host = "{smtp_host}"
smtp_port = 587 # Change if needed.
smtp_username = "{smtp_username}"
smtp_password = "{smtp_password}"
smtp_encrypt = false # Change if needed.

[api]
# Listen to IPv6 by default, and usually IPv4 as fallback too.
address = "::"
